-- 完成版用の追加設定
create table if not exists child_goals (
  id bigint generated by default as identity primary key,
  child_id bigint unique references children(id) on delete cascade,
  monthly_goal integer not null default 2000,
  created_at timestamptz default now()
);

alter table child_goals enable row level security;

drop policy if exists "family goals access" on child_goals;
create policy "family goals access"
on child_goals for all
to anon
using (true)
with check (true);

insert into child_goals (child_id, monthly_goal)
select id, 2000 from children
on conflict (child_id) do nothing;

create unique index if not exists salaries_child_year_month_unique
on salaries(child_id, year, month);
